<a href="https://colab.research.google.com/github/sarthu210/Machine_learning/blob/main/Practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd
import sklearn

In [10]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [12]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [13]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])